/*
 * Copyright 2013-2016 Erudika. http://erudika.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * For issues and patches go to: https://github.com/erudika
 */
package com.erudika.para.core;

import java.io.Serializable;
import java.util.List;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.NotBlank;

/**
 * The core domain interface. All Para objects implement it.
 * @author Alex Bogdanovski [alex@erudika.com]
 */
public interface ParaObject extends Serializable {

    /**
     * The id of an object. Usually an autogenerated unique string of numbers.
     * @return the id
     */
    String getId();

    /**
     * Sets a new id. Must not be null or empty.
     * @param id the new id
     */
    void setId(String id);

    /**
     * The name of the object. Can be anything.
     * @return the name. default: [type id]
     */
    @NotBlank @Size(min = 2, max = 255)
    String getName();

    /**
     * Sets a new name. Must not be null or empty.
     * @param name the new name
     */
    void setName(String name);

    /**
     * The application name. Added to support multiple separate apps.
     * Every object must belong to an app.
     * @return the app id (name). default: para
     */
    String getAppid();

    /**
     * Sets a new app name. Must not be null or empty.
     * @param appid the new app id (name)
     */
    void setAppid(String appid);

    /**
     * The id of the parent object.
     * @return the id of the parent or null
     */
    String getParentid();

    /**
     * Sets a new parent id. Must not be null or empty.
     * @param parentid a new id
     */
    void setParentid(String parentid);

    /**
     * The name of the object's class. This is equivalent to {@link Class#getSimpleName()}.toLowerCase()
     * @return the simple name of the class
     */
    String getType();

    /**
     * Sets a new object type. Must not be null or empty.
     * @param type a new type
     */
    void setType(String type);

    /**
     * The id of the user who created this. Should point to a user id.
     * @return the id or null
     */
    String getCreatorid();

    /**
     * Sets a new creator id. Must not be null or empty.
     * @param creatorid a new id
     */
    void setCreatorid(String creatorid);

    /**
     * The plural name of the object. For example: user - users
     * @return the plural name
     */
    String getPlural();

    /**
     * The URI of this object. For example: /users/123
     * @return the URI
     */
    String getObjectURI();

    /**
     * The time when the object was created, in milliseconds.
     * @return the timestamp of creation
     */
    Long getTimestamp();

    /**
     * Sets the timestamp.
     * @param timestamp a new timestamp in milliseconds.
     */
    void setTimestamp(Long timestamp);

    /**
     * The last time this object was updated. Timestamp in ms.
     * @return timestamp in milliseconds
     */
    Long getUpdated();

    /**
     * Sets the last updated timestamp.
     * @param updated a new timestamp
     */
    void setUpdated(Long updated);

    /**
     * The tags associated with this object. Tags must not be null or empty.
     * @return a set of tags, or an empty set
     */
    List<String> getTags();

    /**
     * Merges the given tags with existing tags.
     * @param tags the additional tags, or clears all tags if set to null
     */
    void setTags(List<String> tags);

    /**
     * Returns the total sum of all votes for this object.
     * For example: (+6) + (-4) = 2
     * @return the total sum of votes
     */
    Integer getVotes();

    /**
     * Sets the total votes for this object.
     * @param votes the number of votes
     */
    void setVotes(Integer votes);

}
